### ISSUE TITLE
change or remove icon

### ISSUE THREAD

**Issue by wbolster** [jabiinfante/gnome-shell-extension-scaleswitcher#1]
hi, thanks for writing this extension!

the icon is not so helpful and it looks a bit odd compared to other icons on the panel. there is also the "x1" or "x2" text, making this extension take up quite a lot if screen space...

since the text is much more useful, perhaps get rid of the icon completely? :)

**Comment by wbolster** [comment]
```
        let gicon=Gio.icon_new_for_string("video-display-symbolic");
```

this makes it nicer already, but my earlier comment still stands :)

**Comment by jabiinfante** [comment]
Hey wouter!

Thanks for your feedback!

I think I will set up a preference so you can choose to see or not to see
the icon.

(I'll take a look at the icon you are suggestion and make a decision about
it)


Thanks!




2017-10-26 17:01 GMT+02:00 wouter bolsterlee <notifications@github.com>:

**Comment by jabiinfante** [comment]
hey @wbolster v5 is finally published:
- a show icon toggle has been added on the prefs menu.
- I followed your advise, and used video-display-symbolic

thanks again ;)
